### ISSUE TITLE
Add more code check rule

### ISSUE THREAD

**Issue by re-f** [actiontech/sqle#63]
目前使用的规则不明确目的，且规则偏少

使用 golangci-lint 做静态代码检查。需要启用的 linter 参考： SQLE confluence space(pageid = 32066003).

子任务跟踪：
- [x] #112
- [x] makefile add docker_lint #161 
- [x] golangci-lint enables errcheck and fixes the problems found #136 
- [x] golangci-lint enables durationcheck and fixes the problems found #145 
- [x] golangci-lint enables nilerr and fixes the problems found #146 
- [x] golangci-lint enables rowserrcheck and fixes the problems found #149 
- [x] golangci-lint enables staticcheck and fixes the problems found #151 
- [x] golangci-lint enables forcetypeassert and fixes the problems found #153 
- [x] golangci-lint enables prealloc and fixes the problems found #154 
- [x] golangci-lint enables deadcode and fixes the problems found #155 
- [x] golangci-lint enables gosimple and fixes the problems found #156 
- [x] golangci-lint enables unconvert and fixes the problems found #160 
- [x] golangci-lint enables errname and fixes the problems found #159 
- [ ] golangci-lint enables dupl and fixes the problems found #162 
- [x] complete execution and problem solving after single task is solved #170

**Comment by drivebyer** [comment]
more see: #112
