### ISSUE TITLE
新增项目管理功能

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#960]
功能简介：以项目为入口支持各种审核功能，不同项目之间资源隔离。变更后在功能的组织上更贴近具体的业务场景，可以根据具体项目的需求定制审核流程、规则模板、白名单等，除了对不同项目的灵活定制外，还方便对项目资源的统一管理。

## 后端变更
- [x] #976 @HuangWeiCen (代码提交, 还没测, 等实例相关功能合了再测, EE部分没改, 等最后一起改)
- [x] 【项目管理】全局规则页面增加项目筛选，筛选时先选项目后，才能选项目所有的数据源。相关接口在 #988 中调整
- [x] 【项目管理】SQL工作台，数据源列表逻辑调整 @HuangWeiCen 
- [x] #1004  @HuangWeiCen (代码提交, 还没测, 等前端合了再测)
- [x] 【项目管理】全局规则模板页面调整。相关接口在 #988 中调整 @ColdWaterLW （后端完成）
- [x] #978 @HuangWeiCen 
- [x] #990 @taolx0 
- [x] #980 @sjjian  
- [x] #984 @HuangWeiCen (最后两个接口是企业版的, 改企业版的时候再处理)
- [x] #988 @ColdWaterLW  （后端完成）
- [x] #993 @HuangWeiCen 
- [x] #998 @HuangWeiCen 
- [x] 【项目管理】dashboard页面逻辑调整
- [x] 【项目管理】报表统计页面逻辑调整
- [x] 【项目管理】license数据源限制逻辑调整

后端开发分支：issue960-project-management

## 优化任务
- [x] #1127
- [x] #1130
- [x] #1131
- [x] #1132

## 升级方案
